#ifndef GAMED_SERVER_H
#define GAMED_SERVER_H

enum GAMED_COMMAND {
    CMD_NOP = 0,
    CMD_INVALID,
	CMD_ERROR,
	CMD_CHAT,
	CMD_PLAYER,
	CMD_GAME,
	CMD_ADMIN,
	CMD_USER_GAME_START
};

enum GAMED_ERRORS {
	GAMED_ERR_GAME_FULL = 0,
	GAMED_ERR_NO_GAME,
	GAMED_ERR_IN_GAME,
	GAMED_ERR_GAME_EXISTS
};

enum GAMED_SUBCMD_CHAT {
	CMD_TALK = 0,
	CMD_WHISPER,
	CMD_EMOTE,
	CMD_ADD_FRIEND,
	CMD_FRIEND_STATUS,
	CMD_REMOVE_FRIEND,
	CMD_CHAT_SENTINEL
};

enum GAMED_SUBCMD_PLAYER {
	CMD_RENAME = 0,
	CMD_PLAYER_SENTINEL
};

enum GAMED_SUBCMD_GAME {
	CMD_LIST_GAMES = 0,
	CMD_LIST_GAME_INSTANCES,
	CMD_CREATE_GAME,
	CMD_JOIN_GAME,
	CMD_LIST_PLAYERS,
	CMD_QUIT_GAME,
	CMD_GAME_SENTINEL
};

typedef struct {
    unsigned command :  8;
    unsigned subcmd  :  8;
    unsigned length  : 16;
} GamedCommand;

#endif
