/*
 * HiLo.java
 *
 * Created on July 6, 2008, 10:16 AM
 */

package gamed.client.HiLo;

import gamed.Server;
/**
 *
 * @author  bruce
 */
public class Plugin extends gamed.Game {
    public static final int GUESS = 0;
    public static final int GIVEUP = 1;
    public static final int TOO_LOW = 2;
    public static final int TOO_HIGH = 3;
    public static final int CORRECT = 4;
    
    private Server server;
    private volatile byte lastGuess;
    
    /** Creates new form HiLo */
    public Plugin(Server s) {
        server = s;
        initComponents();
    }
    
    public void joinedGame() {}
    public void updatePlayers(gamed.Player[] players) {}
    public void renamePlayer(gamed.Player player) {}
    
    public void guess(byte g) {
        lastGuess = g;
        byte cmd[] = { GUESS, g, 0, 0 };
        server.sendGameData(cmd);
    }
    
    public void handleGameData(byte[] cmd) {
        System.err.format("Game data: %d %d\n", cmd[0], cmd[1]);
        Result r;
        switch (cmd[0]) {
            case TOO_LOW:
                r = Result.TOO_LOW;
                break;
            case TOO_HIGH:
                r = Result.TOO_HIGH;
                break;
            default:
                r = Result.CORRECT;
        }
        history.append(lastGuess+" is "+r.toString()+"\n");
}
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        guess = new javax.swing.JSpinner();
        guessButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        history = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Pick a number between 1 and 100");
        jPanel3.add(jLabel1);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        guess.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        jPanel4.add(guess);

        guessButton.setText("Make Guess");
        guessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessButtonActionPerformed(evt);
            }
        });
        jPanel4.add(guessButton);

        quitButton.setText("Give Up");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        jPanel4.add(quitButton);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        history.setColumns(20);
        history.setRows(5);
        jScrollPane1.setViewportView(history);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void guessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessButtonActionPerformed
        byte b = Byte.parseByte(guess.getValue().toString());
        guess(b);

}//GEN-LAST:event_guessButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        server.quitGame();
    }//GEN-LAST:event_quitButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner guess;
    private javax.swing.JButton guessButton;
    private javax.swing.JTextArea history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
    
}
