/*
 * Login.java
 *
 * Created on July 4, 2008, 1:15 AM
 */
import javax.swing.JApplet;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author  bruce
 */
public class Login extends JApplet implements gamed.Server {
    private gamed.Client client;
    private JPanel currentGame;

    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        client = null;
    }

    public java.awt.Image getImage(String name) {
        System.out.println(getDocumentBase());
        return super.getImage(getDocumentBase(), name);
    }
    
    public java.net.Socket getSocket() {
        if (client == null) {
            return null;
        }
        return client.socket;
    }
    
    /**
     * Handles IOExceptions... ok, so its really socket errors
     * I'm not sure what the best thing to do with this is, so for now,
     * I'm just going to disconnect the socket and send you to the connect
     * screen.<br/>
     * Options:
     * <ul>
     * <li>Reconnect and put you on game selection screen (current behaviour)</li>
     * <li>Disconnect entirely and return you to the connect screen</li>
     * <li>Attempt to reconnect to previous game</li>
     * <li>Check the game author's preference (what I'll move to)</li>
     * </ul>
     * 
     * @param e The IOException raised by a socket call
     */
    public void handleIOException(java.io.IOException e) {
        try {
            client.socket.close();
        }
        catch (java.io.IOException ign) {
            // already aborting, just ignore it
        }
        if (currentGame instanceof gamed.Game) {
            ((gamed.Game)currentGame).stop();
        }
        client = null;
        connectButtonActionPerformed(null);
    }
    
    public void quitGame() {
        try {
            if (currentGame instanceof gamed.Game) {
                ((gamed.Game)currentGame).stop();
            }
            client.quitGame();
            showGameCard();
            listGames();
        } catch (java.io.IOException e) {
            handleIOException(e);
        } finally {
            java.awt.Container c = this.getContentPane();
            c.remove(currentGame);
        }
        System.gc();
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameList = new javax.swing.DefaultListModel();
        availableGameList = new javax.swing.JList(gameList);
        jScrollPane2 = new javax.swing.JScrollPane();
        gameInstanceList = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        joinButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Username ");
        jPanel3.add(jLabel1, new java.awt.GridBagConstraints());

        username.setPreferredSize(new java.awt.Dimension(100, 27));
        jPanel3.add(username, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel3);

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        jPanel4.add(connectButton);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, "login");

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("Available Games");
        jPanel8.add(jLabel2);

        jLabel3.setText("Running Games");
        jPanel8.add(jLabel3);

        jPanel5.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        availableGameList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(availableGameList);

        jPanel7.add(jScrollPane1);

        gameInstanceList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(gameInstanceList);

        jPanel7.add(jScrollPane2);

        jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

        createButton.setText("Create Game");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        jPanel6.add(createButton);

        joinButton.setText("Join Game");
        joinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinButtonActionPerformed(evt);
            }
        });
        jPanel6.add(joinButton);

        jPanel5.add(jPanel6, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel5, "games");
    }// </editor-fold>//GEN-END:initComponents

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinButtonActionPerformed
        if (client.createGame("HiLo:test")) {
            currentGame = new gamed.client.HiLo.Plugin((gamed.Server)this);
            java.awt.Container c = getContentPane();
            c.add(currentGame, "currentGame");
            CardLayout cl = (CardLayout) c.getLayout();
            cl.show(c, "currentGame");
        }
}//GEN-LAST:event_joinButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        client = new gamed.Client(getDocumentBase().getHost(), username.getText());
        showGameCard();
        listGames();
}//GEN-LAST:event_connectButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        if (client.createGame("SpeedRisk:test")) {
            currentGame = new gamed.client.SpeedRisk.Display((gamed.Server)this);
            if (currentGame instanceof gamed.Game) {
                ((gamed.Game)currentGame).start();
            }
            java.awt.Container c = getContentPane();
            c.add(currentGame, "currentGame");
            CardLayout cl = (CardLayout) c.getLayout();
            cl.show(c, "currentGame");
        }
    }//GEN-LAST:event_createButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.DefaultListModel gameList;
    private javax.swing.JList availableGameList;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton createButton;
    private javax.swing.JList gameInstanceList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton joinButton;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void listGames() {
        String[] games = client.list_games();
        gameList.clear();
        for (String game : games) {
            System.out.println(game);
            if (game.startsWith("SpeedRisk") ||
                game.startsWith("HiLo")) {
                // TODO Base this filtering on a config file fetched from somewhere
                gameList.addElement(game);            
            }
        }
    }

    private void showGameCard() {
        java.awt.Container c = getContentPane();
        CardLayout cl = (CardLayout) c.getLayout();
        cl.show(c, "games");
    }
}
